import { Card, Typography } from "../../lib";

export const TermsAndConditionCard = () => {
  return (
    <Card size="big" className="mb-0 md:mb-10">
      <Typography type="h5">Terms and Conditions</Typography>
      <br />
      <Typography type="body-regular">
        Protocol Cover protects against smart contract code being used in
        unintended ways (e.g., exploits, hacks) and sudden, severe economic
        events (e.g., oracle manipulation, governance attacks).
      </Typography>
      <br />
      <Typography type="body-regular">
        Exclusions include, but are not limited to:
      </Typography>
      <ul className="list-disc pl-5 space-y-1">
        <li>
          <Typography type="body-regular">Losses due to rug pulls</Typography>
        </li>
        <li>
          <Typography type="body-regular">
            Losses from the de-peg of any asset generated by the Designated
            Protocol
          </Typography>
        </li>
        <li>
          <Typography type="body-regular">
            Losses due to a previously disclosed vulnerability
          </Typography>
        </li>
      </ul>
      <br />
      <Typography type="body-regular">
        Cover applies to all EVM-compatible networks.
        <br />
        Deductible: 5% of the Cover Amount.
      </Typography>
      <br />
      <Typography type="body-regular">
        Claims filing requirements include:
      </Typography>
      <ul className="list-disc pl-5 space-y-1">
        <li>
          <Typography type="body-regular">
            Providing proof of loss when submitting a claim
          </Typography>
        </li>
        <li>
          <Typography type="body-regular">
            Waiting 14 days after the loss event for claims assessors
          </Typography>
        </li>
        <li>
          <Typography type="body-regular">
            Filing a claim up to 35 days after the cover period expires if the
            cover was active during the loss event
          </Typography>
        </li>
      </ul>
      <br />
      <Typography type="body-regular">
        This cover is not a contract of insurance. Cover is provided on a
        discretionary basis with Nexus Mutual members having the final say on
        claims.
        <br />
        Read the complete cover wording <a href="link-to-terms">here</a>.
      </Typography>
    </Card>
  );
};
